### lab4

### fetch entities
GET http://localhost:8080/apartments/all

### create entity
POST http://localhost:8080/apartments/add
Content-Type: application/json

{
    "numberOfRooms": 1,
    "floorNumber": 3,
    "totalFloorsNumber": 3,
    "square": 35,
    "wallType": "wallType",
    "heatingType": "heatingType",
    "apartmentCondition": "apartmentCondition",
    "streetName": "streetName",
    "buildingNumber": "323a",
    "apartmentNumber": 4
}

### update entity
POST http://localhost:8080/apartments/update
Content-Type: application/json

{
    "id": 1,
    "numberOfRooms": 1,
    "floorNumber": 3,
    "totalFloorsNumber": 3,
    "square": 35,
    "wallType": "updatedWallType",
    "heatingType": "updatedHeatingType",
    "apartmentCondition": "apdatedApartmentCondition",
    "streetName": "updatedStreetName",
    "buildingNumber": "323a",
    "apartmentNumber": 4
}

### delete entity
GET http://localhost:8080/apartments/delete/1


### lab3

### api-gateway config
GET http://localhost:8080/configs

### service (instance 1) config
GET http://localhost:8081/configs

### service (instance 2) config
GET http://localhost:8082/configs

### configs in config server
### for service
GET http://localhost:8888/service/default

### for api-gateway
GET http://localhost:8888/api-gateway/default

### config refresh
POST http://localhost:8081/actuator/refresh

### bus refresh
POST http://localhost:8081/actuator/bus-refresh
